M48
; DRILL file {KiCad (6.0.9)} date Sun Jan  8 15:32:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-08T15:32:49+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.305
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.930
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C1.000
%
G90
G05
T1
X-4.6Y-15.45
X-4.6Y-19.6
X-4.6Y-21.75
X-4.6Y-22.7
X-4.5Y-3.8
X-0.7Y-15.3
X0.05Y-3.1
X1.45Y-7.85
X2.15Y-7.15
X4.75Y-21.5
X5.35Y-14.9
T2
X-5.5Y-8.92
X-5.5Y-10.19
X-5.5Y-11.46
X-5.5Y-12.73
X-5.5Y-14.0
T3
X-3.5Y0.0
X-1.0Y0.0
X1.0Y0.0
X3.5Y0.0
T5
X-2.25Y2.4
X2.25Y2.4
T4
G00X-5.85Y1.75
M15
G01X-5.85Y3.05
M16
G05
G00X5.85Y1.75
M15
G01X5.85Y3.05
M16
G05
T0
M30
